# Generated by Django 4.1.5 on 2023-01-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_alter_customers_unique_together_customers_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_pago', models.TextField(max_length=100)),
                ('producto', models.TextField(max_length=300)),
                ('cantidad_producto', models.TextField(max_length=100)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
    ]
