# Generated by Django 4.1.3 on 2023-01-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrators',
            fields=[
                ('id_administrador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_administrador', models.TextField(max_length=100)),
                ('password_administrador', models.TextField(max_length=100)),
                ('rol_administrador', models.CharField(choices=[('A', 'Administrador'), ('S', 'SuperAdministrador')], default=('A', 'Administrador'), max_length=100)),
            ],
        ),
    ]
