# Generated by Django 4.1.5 on 2023-01-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='email',
            new_name='correo',
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('nombre_cliente', 'apellido_cliente', 'correo')},
        ),
    ]
