# Generated by Django 4.1.3 on 2023-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customers_unique_together_customers_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='apellido_cliente',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='nombre_cliente',
            field=models.TextField(max_length=10),
        ),
    ]
